//! What the code generated by `#[tool]` refers to, so that a crate using the
//! macro needs no dependency of its own on `serde`, `schemars` or
//! `async-trait` for the *generated* code (a `#[args]` struct, or your own
//! `#[derive(Deserialize, JsonSchema)]`, still names them itself).
//!
//! Not part of the public API: the paths change with the macro. It is public
//! only because generated code lives in someone else's crate. The macro
//! reaches it as `<crate>::__private`, where `<crate>` is `::adam` (which
//! re-exports this module) or whatever `#[tool(crate = ...)]` names.

use adam_error::Classify;
use serde::de::DeserializeOwned;

use crate::tool::{ToolError, ToolOutput};
use crate::typed::IntoToolOutput;

pub use crate::schema::spec_for;
pub use crate::typed::{IntoToolResult, parse_args};
pub use adam_model::ToolSpec;
pub use async_trait::async_trait;
pub use schemars;
pub use serde;
pub use serde_json::Value;

/// A type the model can fill in: read from its JSON and described to it.
///
/// A blanket trait so that a missing derive is reported as
/// "`Foo` cannot be a `#[tool]` argument" instead of a wall of serde internals.
#[diagnostic::on_unimplemented(
    message = "`{Self}` cannot be a `#[tool]` argument",
    label = "the model's JSON is read into this type and its schema is shown to the model",
    note = "derive `serde::Deserialize` and `schemars::JsonSchema` for `{Self}`"
)]
pub trait ToolArg: DeserializeOwned + schemars::JsonSchema {}

impl<T: DeserializeOwned + schemars::JsonSchema> ToolArg for T {}

/// Compile-time check that `T` is a [`ToolArg`]; never called.
pub const fn assert_tool_arg<T: ToolArg>() {}

/// `#[tool(classify)]`: the result of a tool function whose error is
/// [`Classify`], through [`ToolError::from_classified`].
pub fn classified<T: IntoToolOutput, E: Classify + 'static>(
    result: Result<T, E>,
) -> Result<ToolOutput, ToolError> {
    match result {
        Ok(out) => Ok(out.into_tool_output()),
        Err(e) => Err(ToolError::from_classified(&e)),
    }
}

#[cfg(test)]
mod tests {
    use adam_error::ErrorClass;

    use super::*;

    #[derive(Debug, thiserror::Error)]
    #[error("gone")]
    struct Gone;

    impl Classify for Gone {
        fn class(&self) -> ErrorClass {
            ErrorClass::NotFound
        }
    }

    #[test]
    fn classified_maps_ok_and_err() {
        assert_eq!(
            classified(Ok::<_, Gone>("fine")),
            Ok(ToolOutput::text("fine"))
        );
        assert_eq!(
            classified(Err::<String, _>(Gone)),
            Err(ToolError::Permanent("gone".into()))
        );
    }

    #[test]
    fn a_derived_type_is_a_tool_arg() {
        assert_tool_arg::<String>();
        assert_tool_arg::<Vec<Option<u8>>>();
    }
}
