//! The embedded manifest (generated by `build.rs`, compiled into this crate) and the manifest
//! read from the directory at run time are the same value.
#![allow(clippy::unwrap_used, clippy::expect_used)] // integration tests assert by unwrapping

use adam::agent_fs::{Dir, Layout, ManifestSource, Strictness, Subagent};
use adam_agent_fixture::{AGENT, AGENTS, PACKAGE};

/// The directory `build.rs` embedded.
fn dir() -> Dir {
    Dir::new(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../adam-agent-fs/tests/fixtures/valid"
    ))
    .default_name(env!("CARGO_PKG_NAME"))
}

#[test]
fn the_embedded_package_equals_the_directory() {
    let from_dir = dir().load().unwrap();
    assert!(
        from_dir.diagnostics.is_empty(),
        "{:?}",
        from_dir.diagnostics
    );
    let from_dir = from_dir.into_package(Strictness::Strict).unwrap();

    let embedded = PACKAGE.load().unwrap();
    assert!(embedded.diagnostics.is_empty());
    assert_eq!(embedded.package, from_dir);
    assert_eq!(PACKAGE.layout, Layout::Single);
}

#[test]
fn the_digests_agree_and_verify() {
    let dir = dir();
    let package = dir.load().unwrap().package;
    assert_eq!(AGENTS.len(), package.agents.len());
    for (embedded, owned) in AGENTS.iter().zip(&package.agents) {
        assert_eq!(dir.digest(owned).unwrap(), embedded.digest);
        assert!(embedded.digest.starts_with("sha256:"));
        assert_eq!(embedded.recompute_digest().unwrap(), embedded.digest);
        assert!(embedded.verify().unwrap());
    }
}

#[test]
fn the_static_is_usable_without_parsing() {
    assert_eq!(AGENT.name, "coder");
    assert!(AGENT.instructions.body.contains("{{max_check_cycles}}"));
    let skill = AGENT
        .skills
        .iter()
        .find(|s| s.name == "release-notes")
        .unwrap();
    let style = skill
        .files
        .iter()
        .find(|f| f.path == "references/style.md")
        .unwrap();
    assert_eq!(
        style.bytes,
        std::fs::read(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../adam-agent-fs/tests/fixtures/valid/agent/skills/release-notes/references/style.md"
        ))
        .unwrap()
    );
    // The frontmatter is JSON in the binary and reads with the schema of the directory path.
    assert_eq!(AGENT.frontmatter().unwrap().name.as_deref(), Some("coder"));
    // Nested subagents are embedded too.
    let researcher = AGENT
        .subagents
        .iter()
        .find(|s| s.name() == "researcher")
        .unwrap();
    assert!(matches!(
        researcher,
        adam::agent_fs::EmbeddedSubagent::Local(_)
    ));
    let owned = PACKAGE.to_package().unwrap();
    assert!(
        owned.agents[0]
            .subagents
            .iter()
            .any(|s| matches!(s, Subagent::Remote(_)))
    );
}

#[test]
fn a_changed_resource_changes_the_digest() {
    let dir = tempfile::tempdir().unwrap();
    copy_tree(
        std::path::Path::new(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../adam-agent-fs/tests/fixtures/valid"
        )),
        dir.path(),
    );
    let source = Dir::new(dir.path()).default_name("x");
    let before = source
        .digest(&source.load().unwrap().package.agents[0])
        .unwrap();
    std::fs::write(
        dir.path().join("agent/skills/release-notes/scripts/run.sh"),
        "echo changed\n",
    )
    .unwrap();
    let after = source
        .digest(&source.load().unwrap().package.agents[0])
        .unwrap();
    assert_ne!(before, after);
}

fn copy_tree(from: &std::path::Path, to: &std::path::Path) {
    for entry in std::fs::read_dir(from).unwrap() {
        let entry = entry.unwrap();
        let target = to.join(entry.file_name());
        if entry.file_type().unwrap().is_dir() {
            std::fs::create_dir_all(&target).unwrap();
            copy_tree(&entry.path(), &target);
        } else {
            std::fs::copy(entry.path(), target).unwrap();
        }
    }
}

#[test]
fn a_resource_reads_the_same_bytes_from_the_directory_and_from_the_binary() {
    let dir = dir();
    let from_dir = dir.load().unwrap().package;
    let mut checked = 0;
    for skill in &from_dir.agents[0].skills {
        for resource in &skill.resources {
            let on_disk = dir.read_resource(skill, resource).unwrap();
            let embedded = PACKAGE.read_resource(skill, resource).unwrap();
            assert_eq!(on_disk, embedded, "{resource}");
            checked += 1;
        }
    }
    assert_eq!(
        checked, 2,
        "release-notes has references/style.md and scripts/run.sh"
    );

    // Only what a skill lists is readable: a path out of its directory is refused, not read.
    let skill = &from_dir.agents[0].skills[0];
    for source in [&dir as &dyn ManifestSource, &PACKAGE as &dyn ManifestSource] {
        assert!(
            source
                .read_resource(skill, "../../instructions.md")
                .is_err()
        );
        assert!(source.read_resource(skill, "nope.md").is_err());
    }
    assert_eq!(adam::agent_fs::SKILL_RESOURCE_LIMIT, 1024 * 1024);
}
