//! The generated source: one `static` per package, written as plain Rust.
//!
//! The output is deterministic (sorted inputs, no timestamps, no versions) so that it can be
//! compared with a golden file. Prompts and skill bodies are raw string literals, the text of
//! `mcp.json` is `include_str!` and skill resources are `include_bytes!`, both of an absolute
//! path, so rustc also tracks them.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::manifest::{AgentManifest, Layout, Package, Skill, SkillLayout, Subagent};
use crate::schema::McpConfig;
use crate::{Dir, Error};

use super::BuildError;

/// Render `package`, whose files are under `root`, with generated paths into `crate_path`.
pub(super) fn render(
    package: &Package,
    root: &Path,
    crate_path: &str,
) -> Result<String, BuildError> {
    let mut gen_ = Gen {
        out: String::new(),
        depth: 0,
        root,
        dir: Dir::new(root),
        p: crate_path,
    };
    gen_.package(package)?;
    Ok(gen_.out)
}

struct Gen<'a> {
    out: String,
    depth: usize,
    root: &'a Path,
    dir: Dir,
    /// The path of the crate that holds the `Embedded*` types.
    p: &'a str,
}

impl Gen<'_> {
    fn line(&mut self, text: impl AsRef<str>) {
        for _ in 0..self.depth {
            self.out.push_str("    ");
        }
        self.out.push_str(text.as_ref());
        self.out.push('\n');
    }

    fn blank(&mut self) {
        self.out.push('\n');
    }

    fn open(&mut self, text: impl AsRef<str>) {
        self.line(text);
        self.depth += 1;
    }

    fn close(&mut self, text: impl AsRef<str>) {
        self.depth = self.depth.saturating_sub(1);
        self.line(text);
    }

    fn package(&mut self, package: &Package) -> Result<(), BuildError> {
        let p = self.p;
        self.line(
            "// @generated by adam_agent_fs::build. Do not edit: the next build overwrites it.",
        );
        self.blank();
        self.line("/// The agents of this package, embedded at build time, sorted by name.");
        self.line("#[allow(dead_code)]");
        self.open(format!("pub static AGENTS: &[{p}::EmbeddedAgent] = &["));
        for agent in &package.agents {
            self.agent(agent, "", ",")?;
        }
        self.close("];");
        if package.layout == Layout::Single && !package.agents.is_empty() {
            self.blank();
            self.line("/// The agent of this package (`agent/`).");
            self.line("#[allow(dead_code)]");
            self.line(format!(
                "pub static AGENT: &{p}::EmbeddedAgent = &AGENTS[0];"
            ));
        }
        self.blank();
        self.line("/// The whole package: the layout and the agents.");
        self.line("#[allow(dead_code)]");
        self.open(format!(
            "pub static PACKAGE: {p}::EmbeddedPackage = {p}::EmbeddedPackage {{"
        ));
        self.line(format!(
            "layout: {p}::Layout::{},",
            layout_name(package.layout)
        ));
        self.line("agents: AGENTS,");
        self.close("};");
        Ok(())
    }

    /// `open_prefix` and `close_suffix` wrap the struct literal: `Local(` and `),` inside a
    /// subagent list, nothing and `,` in a slice.
    fn agent(
        &mut self,
        a: &AgentManifest,
        open_prefix: &str,
        close_suffix: &str,
    ) -> Result<(), BuildError> {
        let p = self.p;
        let digest = self.dir.digest(a).map_err(BuildError::from)?;
        let frontmatter = serde_json::to_string(&a.frontmatter)
            .map_err(|e| Error::codec("encode", format!("{} frontmatter", a.name), e))?;
        self.open(format!("{open_prefix}{p}::EmbeddedAgent {{"));
        self.line(format!("name: {},", lit(&a.name)));
        self.line(format!("digest: {},", lit(digest.as_str())));
        self.line(format!("path: {},", self.rel(&a.path)?));
        self.line(format!("frontmatter_json: {},", text(&frontmatter)));
        self.open(format!("instructions: {p}::EmbeddedInstructions {{"));
        self.line(format!("body: {},", text(&a.instructions.body)));
        if a.instructions.parts.is_empty() {
            self.line("parts: &[],");
        } else {
            self.open("parts: &[");
            for part in &a.instructions.parts {
                self.line(format!(
                    "{p}::EmbeddedPart {{ file: {}, body: {} }},",
                    lit(&part.file),
                    text(&part.body)
                ));
            }
            self.close("],");
        }
        self.close("},");
        if a.skills.is_empty() {
            self.line("skills: &[],");
        } else {
            self.open("skills: &[");
            for skill in &a.skills {
                self.skill(skill)?;
            }
            self.close("],");
        }
        if a.subagents.is_empty() {
            self.line("subagents: &[],");
        } else {
            self.open("subagents: &[");
            for sub in &a.subagents {
                match sub {
                    Subagent::Local(local) => {
                        self.agent(local, &format!("{p}::EmbeddedSubagent::Local("), "),")?;
                    }
                    Subagent::Remote(r) => {
                        self.open(format!(
                            "{p}::EmbeddedSubagent::Remote({p}::EmbeddedRemote {{"
                        ));
                        self.line(format!("name: {},", lit(&r.name)));
                        self.line(format!("description: {},", lit(&r.description)));
                        self.line(format!("url: {},", lit(&r.url)));
                        self.line(format!(
                            "auth: {},",
                            match &r.auth {
                                None => "None".to_owned(),
                                Some(crate::RemoteAuth::Bearer { env }) => format!(
                                    "Some({p}::EmbeddedAuth::Bearer {{ env: {} }})",
                                    lit(env)
                                ),
                            }
                        ));
                        self.line(format!("note: {},", text(&r.note)));
                        self.line(format!("path: {},", self.rel(&r.path)?));
                        self.close("}),");
                    }
                }
            }
            self.close("],");
        }
        match &a.mcp {
            None => self.line("mcp: None,"),
            Some(config) => self.mcp(a, config)?,
        }
        if a.schedules.is_empty() {
            self.line("schedules: &[],");
        } else {
            self.open("schedules: &[");
            for s in &a.schedules {
                self.open(format!("{p}::EmbeddedSchedule {{"));
                self.line(format!("name: {},", lit(&s.name)));
                self.line(format!("cron: {},", lit(&s.cron)));
                self.line(format!("timezone: {},", lit(&s.timezone)));
                self.line(format!("agent: {},", lit(&s.agent)));
                self.line(format!("prompt: {},", text(&s.prompt)));
                self.line(format!("path: {},", self.rel(&s.path)?));
                self.close("},");
            }
            self.close("],");
        }
        self.close(format!("}}{close_suffix}"));
        Ok(())
    }

    fn mcp(&mut self, a: &AgentManifest, _config: &McpConfig) -> Result<(), BuildError> {
        let p = self.p;
        let rel = a
            .path
            .parent()
            .map_or_else(|| PathBuf::from("mcp.json"), |d| d.join("mcp.json"));
        self.open(format!("mcp: Some({p}::EmbeddedMcp {{"));
        self.line(format!("path: {},", self.rel(&rel)?));
        self.line(format!("json: include_str!({}),", self.abs(&rel)?));
        self.close("}),");
        Ok(())
    }

    fn skill(&mut self, s: &Skill) -> Result<(), BuildError> {
        let p = self.p;
        self.open(format!("{p}::EmbeddedSkill {{"));
        self.line(format!("name: {},", lit(&s.name)));
        self.line(format!("description: {},", lit(&s.description)));
        self.line(format!("license: {},", option(s.license.as_deref())));
        self.line(format!(
            "compatibility: {},",
            option(s.compatibility.as_deref())
        ));
        if s.metadata.is_empty() {
            self.line("metadata: &[],");
        } else {
            self.open("metadata: &[");
            for (k, v) in &s.metadata {
                self.line(format!("({}, {}),", lit(k), lit(v)));
            }
            self.close("],");
        }
        let tools: Vec<String> = s.allowed_tools.iter().map(|t| lit(t)).collect();
        self.line(format!("allowed_tools: &[{}],", tools.join(", ")));
        self.line(format!("body: {},", text(&s.body)));
        self.line(format!(
            "layout: {p}::SkillLayout::{},",
            match s.layout {
                SkillLayout::Directory => "Directory",
                SkillLayout::Flat => "Flat",
            }
        ));
        self.line(format!("path: {},", self.rel(&s.path)?));
        if s.resources.is_empty() {
            self.line("files: &[],");
        } else {
            self.open("files: &[");
            let dir = s.path.parent().unwrap_or(Path::new(""));
            for resource in &s.resources {
                let abs = self.abs(&dir.join(resource))?;
                self.line(format!(
                    "{p}::EmbeddedFile {{ path: {}, bytes: include_bytes!({abs}) }},",
                    lit(resource)
                ));
            }
            self.close("],");
        }
        self.close("},");
        Ok(())
    }

    /// `path` (relative to the root) as a literal with `/` separators.
    fn rel(&self, path: &Path) -> Result<String, BuildError> {
        let s = path
            .to_str()
            .ok_or_else(|| BuildError::NonUtf8Path(path.to_path_buf()))?;
        Ok(lit(&s.replace('\\', "/")))
    }

    /// `path` (relative to the root) as an absolute path literal.
    fn abs(&self, path: &Path) -> Result<String, BuildError> {
        let full = self.root.join(path);
        let s = full
            .to_str()
            .ok_or_else(|| BuildError::NonUtf8Path(full.clone()))?;
        Ok(lit(s))
    }
}

fn layout_name(layout: Layout) -> &'static str {
    match layout {
        Layout::Absent => "Absent",
        Layout::Single => "Single",
        Layout::Multi => "Multi",
    }
}

fn option(value: Option<&str>) -> String {
    match value {
        None => "None".to_owned(),
        Some(v) => format!("Some({})", lit(v)),
    }
}

/// A string literal, escaped.
fn lit(s: &str) -> String {
    format!("{s:?}")
}

/// A string literal for prose: raw (readable in the generated file) unless the text has a control
/// character other than a newline or a tab, which a raw literal would carry into the source.
fn text(s: &str) -> String {
    if s.chars().any(|c| c.is_control() && c != '\n' && c != '\t') {
        return lit(s);
    }
    let mut longest = 0_usize;
    let mut run = 0_usize;
    let mut after_quote = false;
    for c in s.chars() {
        match c {
            '"' => {
                after_quote = true;
                run = 0;
            }
            '#' if after_quote => run += 1,
            _ => after_quote = false,
        }
        longest = longest.max(run);
    }
    let hashes = "#".repeat(longest + 1);
    let mut out = String::with_capacity(s.len() + 2 * hashes.len() + 3);
    // Writing to a `String` cannot fail.
    let _ = write!(out, "r{hashes}\"{s}\"{hashes}");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_is_a_raw_literal_with_enough_hashes() {
        assert_eq!(text("a b"), "r#\"a b\"#");
        assert_eq!(text("say \"hi\"#"), "r##\"say \"hi\"#\"##");
        assert_eq!(text("x\"##y"), "r###\"x\"##y\"###");
        assert_eq!(text("line\nnext\ttab"), "r#\"line\nnext\ttab\"#");
    }

    #[test]
    fn text_escapes_when_a_raw_literal_would_be_unsafe() {
        assert_eq!(text("a\rb"), "\"a\\rb\"");
        assert_eq!(text("nul\0"), "\"nul\\0\"");
    }

    #[test]
    fn lit_escapes() {
        assert_eq!(lit("a\"b\\c"), "\"a\\\"b\\\\c\"");
    }
}
