#![doc = include_str!("../README.md")]
#![warn(missing_docs)]

pub use adam_agent_fs as agent_fs;
pub use adam_assembly as assembly;
pub use adam_assembly::{
    AGENT_DIR_ENV, AgentDef, AgentFolder, AgentInfo, AliasProblem, Assembly, BoundDef,
    EXTRA_MCP_FILE_ENV, Error as AssemblyError, IntoManifest, Origin, RemoteInfo, TemplateProblem,
    agent_dir, agent_dir_from_env, extra_mcp_file_from_env,
};
// Dev reload, only with the feature `dev`: the agent directory watched and swapped when a file
// changes. See `adam_assembly::LiveAssembly`.
#[cfg(feature = "dev")]
pub use adam_assembly::{LiveAssembly, LiveBuilder, ReloadError, Reloaded};
pub use adam_core as core;
pub use adam_error as error;
pub use adam_llm_agent::*;
// `mcp.json` tools, only with the feature `mcp`: the MCP client (`McpPolicy`, `Env`,
// `McpServers`) that `AgentDef::connect_mcp` uses.
#[cfg(feature = "mcp")]
pub use adam_mcp as mcp;
pub use adam_model as model;
pub use adam_runtime as runtime;

/// The paths the code generated by `#[tool]` refers to. Not part of the API.
#[doc(hidden)]
pub use adam_llm_agent::__private;

/// `#[tool]`: an `async fn` becomes a [`Tool`]. See the [crate docs](crate).
#[cfg(feature = "macros")]
pub use adam_macros::tool;

/// Include the agent that `build.rs` embedded: `adam::include_agent!();` at module level.
///
/// `build.rs` calls `adam_agent_fs::build("agent").emit()`, which writes `OUT_DIR/adam_agent.rs`;
/// this macro includes it. The module then has `AGENTS` (a slice of
/// [`EmbeddedAgent`](agent_fs::EmbeddedAgent)), `AGENT` (the agent of an `agent/` package) and
/// `PACKAGE` (an [`EmbeddedPackage`](agent_fs::EmbeddedPackage), which is a
/// [`ManifestSource`](agent_fs::ManifestSource)). See the [crate docs](crate).
#[macro_export]
macro_rules! include_agent {
    () => {
        ::core::include!(::core::concat!(::core::env!("OUT_DIR"), "/adam_agent.rs"));
    };
}

/// What an agent's source file usually wants: `use adam::prelude::*;`.
pub mod prelude {
    #[cfg(feature = "macros")]
    pub use crate::tool;
    pub use crate::{
        AgentDef, Assembly, AssemblyError, BoundDef, BuildError, FnTool, IntoToolOutput,
        IntoToolResult, Json, Limits, LlmAgent, State, Tool, ToolCtx, ToolError, ToolOutput,
        ToolSet, tools,
    };
}

/// Without the feature `dev` nothing here can watch the agent directory and reload it. (Reading a
/// folder once, at startup, needs no feature: [`AgentFolder`].)
///
/// ```compile_fail,E0432
/// use adam::LiveAssembly;
/// ```
#[cfg(not(feature = "dev"))]
mod dev_is_off {}

/// Without the feature `mcp` there is no MCP client: a build cannot start an MCP server, or reach one,
/// unless it opts in.
///
/// ```compile_fail,E0432
/// use adam::mcp::McpPolicy;
/// ```
#[cfg(not(feature = "mcp"))]
mod mcp_is_off {}
