#![doc = include_str!("../README.md")]
#![warn(missing_docs)]

pub use adam_core as core;
pub use adam_error as error;
pub use adam_llm_agent::*;
pub use adam_model as model;
pub use adam_runtime as runtime;

/// The paths the code generated by `#[tool]` refers to. Not part of the API.
#[doc(hidden)]
pub use adam_llm_agent::__private;

/// `#[tool]`: an `async fn` becomes a [`Tool`]. See the [crate docs](crate).
#[cfg(feature = "macros")]
pub use adam_macros::tool;

/// What an agent's source file usually wants: `use adam::prelude::*;`.
pub mod prelude {
    #[cfg(feature = "macros")]
    pub use crate::tool;
    pub use crate::{
        BuildError, FnTool, IntoToolOutput, IntoToolResult, Json, Limits, LlmAgent, State, Tool,
        ToolCtx, ToolError, ToolOutput, ToolSet, tools,
    };
}
